### ISSUE TITLE
Confirmation error message is shown on confirming screen when user keep the app in background while receiving codes,

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#146]
**Frequency:** 100%
**Repro on build version:** Test flight build V1.12.0(49)
**Does not repro version** Android Internal Build V1.12.0(1004294340)
**Repro on devices:** iPhone 6+ (12.4.5), iPhone XR (14.2)
**Does not repro devices**Samsung M30 (10)
**Pre-condition:** Make sure app should on background while in confirming screen.
  **Repro Steps:**

- Launch the application 
- Go through on-Boarding
- Enter phone number 
- Tap on start button
- Make sure user should keep the app background on confirming screen 
- Open the app after 1 min 
- Observe

 
**Current Behavior:** Confirmation error message is shown on confirming screen.
**Expected Behavior:**  User should able to complete the verification flow
**Impact:** User blocked to complete verification flow.

**Attachment:**
 [ConfirmationError.mp4](https://drive.google.com/file/d/1Y20TF-Kyo2RMuew8mm_AsvGPl2WpLeLE/view?usp=sharing)
[ConfirmationLogs](https://drive.google.com/file/d/1ELgXBBI8mIHEtOge5w0D8bOy81C-j_VY/view?usp=sharing)

**Comment by i1skn** [comment]
I've take a look in the logs and see `Invalid JSON RPC response: "The network connection was lost."`, but I think given behaviour is expected if user backgrounds the app for such a long period of time.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D11](https://valora.testquality.com/project/12128/result/2412156/defect/7834). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D73](https://valora.testquality.com/project/12128/result/2450689/defect/7996).
