### ISSUE TITLE
User was asked to restore account, when account was already set-up before

### ISSUE THREAD

**Issue by i1skn** [celo-org/wallet#148]
### Expected Behavior

This should never happen

### Current Behavior

User was asked to restore account, when account was already set-up before

It's important, because if user has not backed up phrase before, the funds could be lost.

Talk to @asaj for more details.

**Comment by jeanregisser** [comment]
Slack thread: https://celo-org.slack.com/archives/C018VLA3YAK/p1616513041059200

**Comment by jeanregisser** [comment]
Decreasing priority now that we have a mitigation with #195.

**Comment by jeanregisser** [comment]
We found one way to reproduce this:
1. Install Valora <= 1.10.1
2. Create an account
3. Upgrade to Valora 1.12.1
4. Observe that the app shows the account recovery screen

See Slack thread for more details: https://github.com/rt2zz/redux-persist/blob/d7efde9115a0bd2d6a0309ac6fb1c018bf06dc30/src/persistReducer.js#L136-L137
