### ISSUE TITLE
Notification Box does not handle large texts properly

### ISSUE THREAD

**Issue by i1skn** [celo-org/wallet#149]
### Expected Behavior

Correct sizing

### Current Behavior

![WhatsApp Image 2021-03-23 at 18 37 00](https://user-images.githubusercontent.com/6160124/112219704-c1d5d280-8bfb-11eb-8295-1863eb460a30.jpeg)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R74](https://valora.testquality.com/project/12128/testcase/295330/requirement/11618).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.17.0 & Test flight build V1.17.0 and updated the status in test quality tool.

**Test quality tool link:**

-  **Android (4.4.2):**
                 - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450230

- **iOS (14.2):**
                 - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450221

**Query:** 

- [ ] It is observed that, too much gap displayed between actual CTA  text & button button's (e.g. Confirm Now, Dismiss, etc. ) actual position. [Attachment](https://drive.google.com/file/d/1dYoD_dq5GXC8c8IjQPUdKwMmyeWzhFXp/view?usp=sharing). 
**FYI:** Already we have ticket 923 for above observation



Verified On Devices: iPhone SE (14.2), Samsung Galaxy S4 (4.4.2
CC: @i1skn
