### ISSUE TITLE
Verifiquen text is shown instead of confirma on invite user page when the user has set language to Espanol(America Latina)

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#166]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.12.1(1004294341), Test flight build V1.12.1(50)
**Repro on devices:** Samsung Galaxy A9 Pro(8.0),iPhone 6+ (12.4.5). Samsung M40 (40)
**Tested Account:** (515) 444 0200 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)

**Pre-condition:** Go to settings and change the language to Espanol.

 **Repro Steps:**

1. Launch the application & login with a test account.
2. Make sure User should set the app language as Espanol.
3. Go to home screen & click on Send button
4. Enter a mobile number in search field [For Ex: 7156666666]
5. Click on the phone number suggestion appeared
6. Enter the amount in send page
7. Click on the review button.
8. Observe that  verifiquen text is shown instead of confirma is displayed.

**Current Behavior:** Verifiquen is shown instead of confirma on invite user page when the user has set language to Espanol(America Latina).

**Expected Behavior:**  Confirma text should be displayed instead of Verifiquen.

**Impact:** Bad User experience.

**Attachment:** [LatinAmericaVerificationText.png](https://drive.google.com/file/d/1AeZ5umIWZaI1m-DvMBV_ACv4y_hhDWo_/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hey @MuckT we have verified the above issue on latest android internal release build and latest iOS testflight release build V:1.29.2 and observed the issue is fixed

Device : Google Pixel 2XL(11.0), iPhone 12(14.7.1)
Thanks
