### ISSUE TITLE
Add cEUR support to the list of balances in the sidebar menu

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#211]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)

- [ ] Change the contract call;

- [ ] Display the balance. Logic to display the balance:
Nothing changes for users holding only cUSD or cUSD + CELO balance.
If the user holds both cUSD + cEUR balances, both of them will be displayed here. In this case, user will see 3 balances. If the user holds only cEUR balance, they will see only cEUR balance here.

- [ ] Call to fetch current exchange rate to fiat currency of choice.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R8](https://valora.testquality.com/project/12128/testcase/279432/requirement/11242). Do not remove or edit.
