### ISSUE TITLE
Add cEUR transactions to the home feed

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#212]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)
Visually nothing changes, since all transactions are displayed in the fiat currency of choice. 

To do:
- [ ] Adjust feed items to display cEUR conversions.

External dependencies:
Blockscout & Blockchain APIs support cEUR

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R7](https://valora.testquality.com/project/12128/testcase/279431/requirement/11241). Do not remove or edit.

**Comment by Celoqa** [comment]
Hey @aleksey-nov Can you please give us access to `Design in Figma` this link so that we can add test cases for this feature by referring Figma screens? 
Thanks..!!

**Comment by aleksey-nov** [comment]
done!

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R40](https://valora.testquality.com/project/12128/testcase/287389/requirement/11467).
