### ISSUE TITLE
Add cEUR support to Transaction details screens

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#213]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)
Transaction details screens stay pretty much unchanged. The change in all of these screens is to the final line showing the underlying currency and rate. When sending from cEUR balance, the line should be updated to “Celo Euros @ €[Rate]”.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R6](https://valora.testquality.com/project/12128/testcase/279430/requirement/11240). Do not remove or edit.
