### ISSUE TITLE
Add cEUR support to the Send flow

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#214]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)

Nothing changes for the user holding only cUSD/cEUR balance.

If the user holds two balances, when they start the send flow, the recently used balance will be chosen by default. At the top of the Send screen it will say which wallet/balance is selected now and how much money is available on this balance (in fiat value). There is an arrow suggesting that the area is tappable. On tap, users will be allowed to choose from which stable coin wallet they want to make a transaction (new bottom sheet element, yay!).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R5](https://valora.testquality.com/project/12128/testcase/279429/requirement/11239). Do not remove or edit.

**Comment by aleksey-nov** [comment]
I have added events to be implemented to Figma doc in comments.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R49](https://valora.testquality.com/project/12128/testcase/293451/requirement/11543).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R50](https://valora.testquality.com/project/12128/testcase/293455/requirement/11544).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R51](https://valora.testquality.com/project/12128/testcase/293456/requirement/11545).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R52](https://valora.testquality.com/project/12128/testcase/287394/requirement/11546).
