### ISSUE TITLE
Add cEUR support to the Request flow

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#215]

**Comment by aleksey-nov** [comment]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)

In the request flow, the decision of which stable coin to use is up to the person who sends the money. The person who receives the money creates a request in fiat currency, the same as now.

If the person who sends money holds only one balance, their sending flow stays as it is now. If they hold 2 stable currency balances, the most recently used coin will be chosen by default and there will be an edit button on the transaction confirmation screen that will allow changing the balance.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R9](https://valora.testquality.com/project/12128/testcase/279428/requirement/11243). Do not remove or edit.
