### ISSUE TITLE
Add cEUR support to buy/sell CELO flow

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#216]
[Design in Figma](https://www.figma.com/file/oLgp5ZQamOR1vHRWHMcOpv/Celo-Euro?node-id=1%3A3)

No changes if the user holds 1 balance. 
If the user holds two balances, when they start the send flow, the recently used balance will be chosen by default. At the top of the screen,  it will say which wallet/balance is selected now and how much money is available on this balance (in fiat value). There is an arrow suggesting that the area is tappable. On tap, users will be allowed to choose from which stable coin wallet they want to make a transaction (new bottom sheet element, yay!).

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R3](https://valora.testquality.com/project/12128/testcase/279426/requirement/11237). Do not remove or edit.
