### ISSUE TITLE
Nothing happens when user tapping on “Open in Playstore in app” button on “Valoraapp.co”. 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#226]
**Frequency:** 100%
**Repro on build version:** Play Store build V1.12.2
**Repro on devices:** Samsung M40 (10.0), Samsung Galaxy A5(7.0)
**Login credential:**  [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)
  **Repro Steps:**

1. Launch the application & login with test account 
2. Make sure user should able to see the Enjoying Valora in app notification
3. Tap on Open button in In-App notification
4. Tap on Open in play store app button on valoraapp.co page 
5. Observe nothing happens,

**Current Behavior:** Nothing happens when user tapping on “Open in Playstore in app” button.
**Expected Behavior:** User should redirect to Playstore by tapping on “Open in Playstore in app” button
**Impact:** User get blocked to Redirect to playstore & rate the app .
**Attachment:** [OpenPlaystoreButton.mp4](https://drive.google.com/file/d/16pYsSikVc1TpoYTpWoqWFW08ajXTtA7a/view?usp=sharing)

**Comment by aleksey-nov** [comment]
Will be fixed in #7929

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D35](https://valora.testquality.com/project/12128/result/2418343/defect/7879).

**Comment by Celoqa** [comment]
Hi @gnardini I have verified this issue using latest Android internal build V1.16.1 & observed that issue is still reproduced.
**Verified On Devices:** Redmi Note 8 (9.0),Redmi Note 8 (10.0), Vivo V11 pro (10)
Thanks..!!

**Comment by aleksey-nov** [comment]
Not reproducable anymore
