### ISSUE TITLE
Investigate Persona React Native Documentation

### ISSUE THREAD

**Issue by nityas** [celo-org/wallet#236]
### Expected Behavior

Persona is a KYC provider we would be looking to integrate within the Valora experience. While we're determining where in the app this will be surfaced, it may be worthwhile looking into the docs so we can ask the persona team any questions

General Provider Info: https://withpersona.com/
RN Docs Link: https://docs.withpersona.com/docs/react-native-sdk-integration

**Comment by tarikbellamine** [comment]
Closed in favor of https://app.zenhub.com/workspaces/cico-sprint-board-6010683afabec1001a090887/issues/celo-org/celo-monorepo/7896
