### ISSUE TITLE
[Device Specific] “Please buy and sell responsibly”  walkthrough screen’s description overlaps on Carousel from CELO walkthrough screens.

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#240]
**Frequency:** 100%
**Repro on build version:** Play Store build V1.12.2
**Does not repro version** App store build V1.12.2
**Repro on devices:**  LG K7i(6.0)
**Does not repro devices** Samsung Galaxy S4(4.4.2), HTC Desire 526G+ (4.4.2) , samsung galaxy S4(5.0.1), Samsung Galaxy A5(7.0), Samsung Galaxy M31 (10.0),  iPhone XR (14.4.1), iPhone 6+ (12)
 **Tested Account:**  (715) 575 8688 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B12)
 **Repro Steps:**
1. Launch the application and login with a test account.
2. Tap on the Hamburger menu.
3. Now tap on the CELO option.
4. Now users should be able to see walkthrough screens.
5. Now start swiping on the LHS side until the “Please buy and sell responsibly” walkthrough screen display.
6. Observed that,

**Current Behavior:**  Description of walkthrough screen overlaps on Carousel.
**Expected Behavior:**  Description should not overlap on Carousel.
**Impact:** Bad user experience.
**Attachment:**  [CouroselOverplapsOn4thWalkthrough.mp4](https://drive.google.com/file/d/1O_a_nPmCC7IRVMbH5g8abruU4y7VtVMJ/view?usp=sharing)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R72](https://valora.testquality.com/project/12128/testcase/295328/requirement/11616).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.17.0 & Test flight build V1.17.0 and updated the status in test quality tool.

**Test quality tool link:**

- **Android:**
      - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450228

- **iOS:**
      - https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450219
  
**Verified On Devices:** iPhone SE (14.2), Samsung Galaxy S4 (4.4.2),
