### ISSUE TITLE
Label Moola Market's address in the Valora Transaction Feed

### ISSUE THREAD

**Issue by nityas** [celo-org/wallet#245]
### Expected Behavior

Deposits from 0xaf106f8d4756490e7069027315f4886cc94a8f73 should be labeled as coming from "Moola Market" - logo in progress

### Current Behavior

deposits are not labeled

**Comment by gnardini** [comment]
Added them to Firebase with their Twitter icon, but I'd be happy to change it if they want a different or higher quality one. Leaving open to wait on confirmation on the logo.

![IMG_2A897353B9D7-1](https://user-images.githubusercontent.com/6062888/115467762-643ba280-a208-11eb-9012-3a129589e41a.jpeg)

**Comment by tarikbellamine** [comment]
I think we can consider this done. We can always add a hire resolution image remotely later if we want to.
