### ISSUE TITLE
Notify user to send test transaction (0.01) before they send the full amount to the new address.

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#250]
**What's important about this?**
Users are sending tokens to the exchange that is not supporting the given token, as a result, users lose their funds.

From the support team: 

We have started to track lost funds discretely in Zendesk to help back up this need; I would recommend that we add in-app messaging the first time sending to a phone number or account number. The messaging would be an encouragement to send a test .01 before proceeding with the primary transaction where we could also include a warning about token types, etc.

From the support ticket: 
"It seems that Coinbase will try to solve something but also if I send CUSD to Coinbase and I try to put it in the CELO wallet your App Valora should warn me that the wallets do not match like most sites do, I should not let the shipment do that very poorly done."

**What is done?**
There is a popup with the next text (not a final version!):
"You are sending <token_name> to an address outside of Valora. Make sure that the exchange/wallet you are sending to supports <token_name>. If you are not sure, we advise to send test transaction of 0.01 first"

This popup should be displayed when user send funds to account number, not the phone number.

**What's involved in doing this?**
Implementing popup that is triggered when the above conditions are met.

**Comment by aleksey-nov** [comment]
More context here: https://www.notion.so/clabsco/Rising-Issues-April-2021-2dc2d51d86b044728cc290025be236dc

**Comment by aleksey-nov** [comment]
Design: https://www.figma.com/file/icLDOiBBWAFZRwssfAHSIy/Sending-to-Address?node-id=402%3A893

**Comment by Celoqa** [comment]
Hey @aleksey-nov Can you please give access to us for `Design: https://www.figma.com/file/icLDOiBBWAFZRwssfAHSIy/Sending-to-Address?node-id=402%3A893` this link so that we can check related all changes in Figma screen ?
Thanks..!!

**Comment by aleksey-nov** [comment]
@Celoqa done
