### ISSUE TITLE
Continues loading indicator is shown when the user taps on the  “Transak” option while adding funds from the “Add & Withdraw” tab.

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#262]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.13.0(1004294348 | Test Flight build V1.13.0(55)
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2
**Repro on devices:** Google Pixel XL (8.1), Galaxy M31 (10) , iPhone 6+ (12.4), iPhone XR (14) 
**Testing Account:**   515 444 0200/ [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B5)   

 **Repro Steps:**
1. Launch the application & login with a test account.
2. Tap on the Hamburger menu. 
3. Tap on Add and Withdraw option. 
4. Tap on Add Funds options. 
5. Tap on the “Next”  button after selecting “Currency” and pay with options. 
6. Enter an amount and tap on “Next” button i.e Amount 20 or above 
7. Tap on “Transak” option and observe continuous loading indicator is shown 

**Current Behavior:**  Continuous loading indicator is shown 
**Expected Behavior:**  Respective webview screen should open. 
**Investigation:** Issue also repro for Moonpay and Ramp “Add funds” option. 
**Impact:** Users are blocked to add funds from Transak , Moonpay & Ramp. 
**Attachment:**  [Android_AddFunds_Issue.mp4](https://drive.google.com/file/d/1eUEMgmSQWJ8h3SDVQBa9Hjsu8yue9Euo/view?usp=sharing) (Bug observed after 5 sec)

**Comment by tarikbellamine** [comment]
This should be fixed. I just needed to deploy our service to the production environment :)

**Comment by Celoqa** [comment]
Hi @tarikbellamine we have verified this issue on latest Android internal build V1.13.0 (1004294348) & Test Flight build V1.13.0 (55) and found issue is fixed.

- User should redirect to transak page after tapping on Transak button

**Comment by MuckT** [comment]
Non-reproducible on V1.13.0 (Alfajores Testnet)
Attachment: [iOS_AddFunds_Issue.png](https://drive.google.com/file/d/1wOIRvJkOBDdZZ3e1yWcu3N0D-AVjxMF-/view?usp=sharing)
