### ISSUE TITLE
Add Analytics events when navigating to Rewards screen

### ISSUE THREAD

**Issue by gnardini** [celo-org/wallet#269]
### Expected Behavior

There are analytics events fired when a user goes to the Rewards screen

### Current Behavior

There are no such events

**Comment by aleksey-nov** [comment]
@michellewong793 please find event names in the doc: https://docs.google.com/spreadsheets/d/1rnSj4fjCNE1Z0Qxjn_cpBe_AFKQgS4RlKo2NLuYAahs/edit?usp=sharing
