### ISSUE TITLE
Account number display should adjust with font size changes

### ISSUE THREAD

**Issue by isabellewei** [celo-org/wallet#271]
### Expected Behavior

Account number should be displayed gracefully throughout Valora, with font size changes

### Current Behavior

There is weird spacing when the user changes the font size
https://celo-org.slack.com/archives/C018VLA3YAK/p1619045702267100

**Comment by tarikbellamine** [comment]
I think this can be generalized to "gracefully handle font size changes throughout Valora"

**Comment by tarikbellamine** [comment]
Closed in favor of #109
