### ISSUE TITLE
Closing The App During Third Attestation Code Causes Issues

### ISSUE THREAD

**Issue by MuckT** [celo-org/wallet#272]
### Reproduction Steps

1. Create a new Account.
2. Connect a Phone Number.
3. Wait for phone number to confirm with app open.
4. Input the first two codes sent via sms to your phone number.
5. **Input the third attestation code and quickly return to the home screen.**
6. Reload the App.
7. Navigate to 'CELO' in the drop down menu and complete the education flow.
8. Open Exchange.

### Expected Behavior

Exchange opens correctly or the phone number is not marked as verified.

### Current Behavior

Closing the app during the 3rd attestation code is validating shows the number as verified; however, no number appears to be attached to the wallet. Errors are thrown when opening the exchange.

### Impact to user
Code verification can take awhile as such users are naturally included to close the app.

Attachment: [iOS_Attestation_Issue.mov](https://drive.google.com/file/d/1cIn0BObbTpWIgguHHyBUIkfR8nWvG3sd/view?usp=sharing)

**Comment by Celoqa** [comment]
Hey @MuckT I have verified this issue using Android internal build V1.13.0 (1004294348) & Test Flight build V1.13.0 (55) & observed following:

 
- User able to see phone number in Hamburger menu even we close app at a time of pasting third code & after reloading app. And at the same time In-App CTA also showing to verify phone number. Also we have observed same issue when user complete & close Captcha flow & return back to Valora Home screen and we have already raised issue for same #7124

 
- Also we have observed that CELO Exchange page get loaded completely without any error after interrupting flow while entering third code.

**Attachment:** [NoErrorForExchnageScreen.mp4](https://drive.google.com/file/d/1Pyuel32FdockKzCeWKsjN-z_k9Cjtt-M/view?usp=sharing)
**Verified On Devices:** iPhone 6 (12.4.7), iPhone SE (14.2)

**Note:** We are unable to open attachment. Can you please give access for same ?

**Comment by tarikbellamine** [comment]
Closed in favor of https://github.com/celo-org/celo-monorepo/issues/6473

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R18](https://valora.testquality.com/project/12128/testcase/282019/requirement/11272). Do not remove or edit.
