### ISSUE TITLE
[Design] Notify users about importance to check if recieving account supports such token.

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#273]
We need to think through how we want to mitigate the cases when the user sends tokens to an exchange that is not supporting this token type. More info in this issue: https://app.zenhub.com/workspaces/wallet-backlog-board-60092d006a84e3001d0d5936/issues/celo-org/wallet/250

**Comment by coreycelo** [comment]
Designs: [Figma](https://www.figma.com/file/icLDOiBBWAFZRwssfAHSIy/Sending-to-Address?node-id=402%3A893)
