### ISSUE TITLE
Notification to reclaim from escrow appears inconsistently

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/wallet#280]
### Expected Behavior
If it has been over an hour and the recipient has not already claimed their payment, the user should have the option to reclaim from escrow.

### Current Behavior
Some users are reporting not seeing the reclaim notification when they are supposed to.

Context: https://celo-org.slack.com/archives/C01QQPXC5U6/p1619042282022400

**Comment by jeanregisser** [comment]
Should be fixed with #351
