### ISSUE TITLE
[Design] Add visual idicator that user can copy the address by tapping on it in the side menu

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#302]
### Expected Behavior

There is a visual indication that user can copy the account key from the side menu. Should be a copy icon or just say in plain text "Tap to copy"
### Current Behavior

Users are not aware that they can copy the account key by tapping over it. As a result, they type it in manually and do mistakes > send the funds to non-existing addresses. More context here: https://celo-org.slack.com/archives/C0134SBQTQR/p1619797847006600

**Comment by coreycelo** [comment]
Doesn't look like I'm able to edit this particular issue to add designs up top. Designs are here: [Figma](https://www.figma.com/file/yEhjVFoX8fVniEzazXCzvF/Account-Number-Display?node-id=1%3A3).

Consolidates this issue with some related formatting issues around handling large text sizes.
