### ISSUE TITLE
Add visual indicator that user can copy the address by tapping on it in the side menu

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#303]
Expected Behavior
There is a visual indication that user can copy the account key from the side menu. Should be a copy icon or just say in plain text "Tap to copy"

Current Behavior
Users are not aware that they can copy the account key by tapping over it. As a result, they type it in manually and do mistakes > send the funds to non-existing addresses. More context here: https://celo-org.slack.com/archives/C0134SBQTQR/p1619797847006600

- [ ] Add visual indicator according to the design specs created here: https://app.zenhub.com/workspaces/wallet-backlog-board-60092d006a84e3001d0d5936/issues/celo-org/wallet/302

- [ ] Add analytics event when users tap over account number: `account_number_copied`

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R39](https://valora.testquality.com/project/12128/testcase/287388/requirement/11466).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest android build V1.16.0 & Testflight build V1.16.0(66) and updated the status in testqulaity tool.

**Testquality tool link:**

**Android:**
- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432161

**iOS:**
- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432189

CC: @isabellewei

**Comment by Celoqa** [comment]
Hi @MuckT, We have verified this issue on Latest android build V1.16.0 in Android 11.0 and everything is working as expected.
**Device Details:** Google Pixel 4a(11.0)
