### ISSUE TITLE
[Query]  “Loading indicator” is shown for 2seconds on "Receive funds in:" section every time when user tap on Add funds/Cash out.

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#322]
**Frequency:** 100%
**Repro on Devices:** Samsung Galaxy A5(7.0), iPhone XR (14.4), iPhone 6+(12.4.5), Vivo V11 pro (10)
**Repro on build version:** Android internal build V1.13.1(1004294349) & Test Flight build V1.13.1(56).
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2
**Login credential :** (515) 808 5659 / [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B69)
**Repro Steps:**

1. Launch the application and login with a test account.
2. Go to Home screen 
3. Tap on Hamburger menu
4. Tap on Add and withdraw
5. Tap on Addfunds/Cash out
6. Observe loading indicator in "Receive funds in"

**Query :** “Loading indicator should not show for every time when user tap on funds/Cash out
**Attachment:** [LoadingIndicator.mp4](https://drive.google.com/file/d/1XNHw-ep4NIpesQ5wtlqMktER8v_ncdR7/view?usp=sharing)

**Comment by MuckT** [comment]
@Celoqa This is intentional behavior; Closing this bug.

**Comment by Celoqa** [comment]
Thanks @MuckT for clarification.
