### ISSUE TITLE
Toggling Tracking from iOS Settings During Onboarding Causes Infinite Spinner on Phone Number Verification Step

### ISSUE THREAD

**Issue by MuckT** [celo-org/wallet#336]
### Current behavior

Changing Data tracking toggle in Settings > Privacy > Tracking During Phone Verification produces an infinite spinner during step 4 of the onboarding flow.

### Desired behavior

Toggling the App Tracking iOS Settings either 'on' or 'off' should not noticeably impact the onboarding flow.

### Steps to Reproduce

1. Launch the app on the iOS device.
2. Select 'Ask App Not to Track' or 'Allow'.
3. Continue Education onboarding and complete steps 1 -3.
4. Make sure you're on step 4.
5. Background the app and navigate to Settings > Privacy > Tracking and flip the toggle for Valora.
6. Attempt to reopen the app - **crashes several times.**
7. When does Valora opens user is served step 4 of 5 (phone verification) with an infinite spinner.

### Versions
Valora 1.14.0 on iPhone 11 iOS 14.5

### Attachments
[Video](https://drive.google.com/file/d/1XfZ4ni7Fpw57Yt6iC299-bOY9lfIZZvL/view?usp=sharing)
[Logs](https://drive.google.com/file/d/1XiTyufk7UM_sUQdLVWIwHQV1X6CfPZqN/view?usp=sharing)

### Notes
If Komenci is down user is redirected to the verification step from the home section with the same infinite spinner (unless they have previously skipped)

### Workaround
Once the user successfully launches to app they can skip phone number verification and navigate to the home screen.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R14](https://valora.testquality.com/project/12128/testcase/280017/requirement/11266). Do not remove or edit.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R15](https://valora.testquality.com/project/12128/testcase/280018/requirement/11267). Do not remove or edit.

**Comment by jeanregisser** [comment]
Thanks @MuckT 
I think there are several issues here, but none are directly related to the ATT popup.
I'm unable to reproduce the crash on the release version of Alfajores.

Issues observed (except crash) were caused by Komenci being down for Alfajores.
I propose we rename the issue to:
**"Infinite Spinner on Phone Number Verification Step when relaunching app when Komenci is down"**

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on latest Test Flight build V1.14.0(59) and not able to repro the crash.
**Device:** iPhone 8 (14.5.1)
