### ISSUE TITLE
“Enter pin” is asking every time when user kill & relaunch the app if user signup through create new account. . 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#339]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.14.0 (1004294350) & Test Flight build V1.14.0(58)
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2, Test Flight build V1.13.1(56).Android internal build V1.13.1(1004294349) 
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7),iPhone XR (14.2), iPhone 6+(12.4.5) , 
**Pre-Condition:** 

- Make user user should Complete phone number verification through create new account .
- Make sure “Require PIN on app open” toggle button should disable

  
   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. Enter phone number 
6. Tap on start button/ Skip the verification flow 
7. Wait for phone number confirming screen
8. Complete verification flow 
9. Kill & relaunch the app 
10. Observe enter pin is shown

 

**Current Behavior:** Enter pin is asking everytime when user kill & relaunch the app. 
**Expected Behavior:**  Enter pin should not ask  everytime when user kill & relaunch the app if “Require PIN on app open” toggle button is disable
**Observation:** Enter pin is not asked when user signin through restore account. 
**Impact:** Bad user experience . 
**Attachment:**  [EnterPIN.mp4](https://drive.google.com/file/d/1MzNyllu4bIdTtwvYAZU-qeAOSgsaeroy/view?usp=sharing)

**Comment by jeanregisser** [comment]
Thanks, it seems this is a side effect of the changes for CIP8.
It should only happen when the user skips verification or if the user doesn't send a transaction after creating their account.
I'll let @isabellewei confirm and share what we should do about this.

**Comment by Celoqa** [comment]
thanks @jeanregisser for giving more information Sure, we will wait for @isabellewei confirmation.

**Comment by Celoqa** [comment]
Hi @gnardini @jeanregisser We have verified this issue on latest internal  build V1.14.1 & Test Flight build V1.14.0(59) and found issue is fixed.
- Enter pin is not asked every time when user kill & relaunch the app.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D3](https://valora.testquality.com/project/12128/result/2397005/defect/7768). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D4](https://valora.testquality.com/project/12128/result/2396997/defect/7775). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D5](https://valora.testquality.com/project/12128/result/2401635/defect/7777). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D6](https://valora.testquality.com/project/12128/result/2396975/defect/7778). Do not remove or edit.

**Comment by Celoqa** [comment]
https://valora.testquality.com defect [D7](https://valora.testquality.com/project/12128/result/2397003/defect/7779). Do not remove or edit.
