### ISSUE TITLE
“Continuous loading” indicator is show on phone number page when user kill & relaunch the app if user is on Phone number page. 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#341]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.14.0 (1004294350) & Test Flight build V1.14.0(58)
**Does not repro version** App Store build 1.12.2	, Play Store build 1.12.2, Test Flight build V1.13.1(56).Android internal build V1.13.1(1004294349) 
**Repro on devices:** One plus 6T (10),Samsung Galaxy Note 5(7),iPhone XR (14.2), iPhone 6+(12.4.5) , 

   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. KIll & relaunch the app when user is on phone number 
6. Enter pin 
7. Observe 

**Current Behavior:** Loading indicator is shown. 
**Expected Behavior:**  Phone number page should show 
**Impact:** User get blocked to continue verification. 
**Attachment:**  [LoadingIndicatoronPhoneNumberPage.mp4](https://drive.google.com/file/d/1BeXJQRPl5YJwY-0oePAHyl3SxotPmVh3/view?usp=sharing)
[Logs](https://drive.google.com/file/d/1jyQxdpN3gMWZQ3qe3wUn9u-NZdU8mwA0/view?usp=sharing )

**Comment by jeanregisser** [comment]
From what I see there's some logic that is applied during the focus event of the `VerificationEducationScreen`,
and because of the PIN screen being triggered (#339), it stays in an indefinite loading loop.

**Comment by Celoqa** [comment]
Thanks @jeanregisser for giving information We will check this issue once (#339) got fixed.

**Comment by Celoqa** [comment]
Hi @gnardini @jeanregisser We have verified this issue on latest internal build V1.14.1 & Test Flight build V1.14.0(59) and found issue is fixed.
- Phone number page is loaded when user kill & relaunch the app if user is on phone number page.
