### ISSUE TITLE
Licenses page is not loaded completely when the user clicks on the licenses option in settings page.

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#343]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.14.0 (1004294350) 
**Does not repro version** Test Flight build V1.14.0(58), Play Store build 1.12., Test Flight build V1.13.1(56).Android internal build V1.13.1(1004294349) 
**Repro on devices:** Samsung Galaxy Note 5(7) , Vivo V11 pro (10)
   **Repro Steps:**

1. Launch the application 
2. Complete onboarding education
3. Tap on create new account 
4. Enter pin
5. Enter phone number 
6. Tap on start button/ Skip the verification flow 
7. Click on Hamburger menu
8. Scroll down and click on settings option
9. Scroll the settings page down and click on the licenses option
10. Observe the licenses page

**Current Behavior:** Licenses page is not loaded completely when the user clicks on the licenses option in settings page
**Expected Behavior:**  The licenses page should be completely loaded with all the relevant data
**Observation:** **[iOS]**
- Data in licenses page is loaded completely when user tap on license button in settings page 
- Loading indicator is not shown when user tap on licenses page 

**Impact:** User get blocked/not able to see data in licenses page . 
**Attachment:**  [Licensespage.png](https://drive.google.com/file/d/1G-jBkBI5ouCR7gcydWWlajcpYsGL70Ea/view?usp=sharing)

**Comment by MuckT** [comment]
@Celoqa can you retest on V1.14.1. I am not able to reproduce this defect.
Attachement: [Licenses - Android.png
](https://drive.google.com/file/d/1V7fZ7KtZmJm2WUV32WWkYfrhfPGlgHE1/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on latest android internal V1.14.1 and found issue is fixed so, closing this ticket.
Thanks!
