### ISSUE TITLE
Unable to see phone number for contacts with multiple phone numbers

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/wallet#349]
### Current behavior

Unable to see phone number for contacts with multiple phone numbers, making it impossible to distinguish them.

See Slack thread: https://celo-org.slack.com/archives/C018VLA3YAK/p1620685865392600

### Desired behavior

Phone number should be shown under each contact.

### Steps to Reproduce

1. Have a contact with 2 phone numbers
2. Go to the send screen and notice you see the contact twice, but it's impossible to tell the actual phone number as only the number is shown.

### Versions

Valora 1.14.0
Valora <= 1.14.0 is not affected by this issue.

**Comment by Celoqa** [comment]
Hi @gnardini @jeanregisser We have verified this on latest internal build V1.14.1 & Test Flight build V1.14.0(59) and observe the followings.
- User is able to see the Phone number on below contacts if user save same contact with 2 phone numbers.
