### ISSUE TITLE
Users appear as verified when they aren't

### ISSUE THREAD

**Issue by gnardini** [celo-org/wallet#375]
### Current behavior
Some users have reported not receiving the balance-based rewards even though they were verified and had the minimum required balance. However, upon closed inspection, they show up as verified in the app but have only 2 successful attestations.

### Desired behavior
Users never show up as verified unless they have 3 completed attestations.

### Steps to Reproduce
Undetermined. The hypothesis is that this is due to a bug on 1.13

### Versions

This issue started after the 1.13 update that had other verification-related issues.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R16](https://valora.testquality.com/project/12128/testcase/282020/requirement/11270). Do not remove or edit.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R17](https://valora.testquality.com/project/12128/testcase/282019/requirement/11271). Do not remove or edit.
