### ISSUE TITLE
Improve "Shake for support" experience

### ISSUE THREAD

**Issue by aleksey-nov** [celo-org/wallet#395]
Users trigger contact support by shaking their device when they don't expect that to happen. It is friction in the user's experience and creates meaningless support tickets.

More context in thread: https://celo-org.slack.com/archives/C018VLA3YAK/p1619540156313900

Proposed solution: show a modal that will explain what had happened and will allow the user to contact support or go back to the screen where they have triggered it. Design in Figma: https://www.figma.com/file/mlLC6CfvtEgcpX91gmfHFR/Shake-to-Contact?node-id=1%3A3

**Comment by Celoqa** [comment]
Hey @aleksey-nov Can you please give access to `Design in Figma: https://www.figma.com/file/mlLC6CfvtEgcpX91gmfHFR/Shake-to-Contact?node-id=1%3A3` link so that we can cross check for the same ?
Thanks.. :)

**Comment by Celoqa** [comment]
Thanks @aleksey-nov able to access now.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R60](https://valora.testquality.com/project/12128/testcase/286487/requirement/11554).

**Comment by Celoqa** [comment]
Hi @muckti have verified this issue on Latest android build V1.16.0 & Testflight build V1.16.0(66) and updated the status in test qulaity tool.
**Test Quality tool link:**

**Android:**

- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432217

**iOS:**

- https://valora.testquality.com/project/12128/plan/20854/run/148956/result/2432226

**Verified On Devices:** iPhone SE (14.2), Redmi Note 8 (9.0)
CC: @aleksey-nov
