### ISSUE TITLE
Second Attestation UI glitch

### ISSUE THREAD

**Issue by isabellewei** [celo-org/wallet#404]
### Current behavior
https://github.com/celo-org/wallet/pull/391#issuecomment-845918623
It causes a code that was automatically pasted to disappear briefly and the tick shows up later if the code is completed successfully. Behind the scenes the user is still being verified successfully (this is a UI-only error) 

### Versions

1.14.2

**Comment by isabellewei** [comment]
In bugapalooza I had a similar glitch where the 3rd attestation box showed as loading before the 2nd attestation box finished loading, and then went back to the initial white Enter Code state before it autoloaded the 3rd attestation code and loaded it.

**Comment by jeanregisser** [comment]
Fixed by #432
