### ISSUE TITLE
 [Query] “Review button is shown Disable & No “Error” message is shown when user cashout celo. 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#453]
**Frequency:** 100%
**Repro on build version:** Test Flight build V1.14.3(62), Android  internal  build V1.14.3, Android internal build V1.15.0 & Testflight build V1.15.0(63) 
**Repro on devices:** iPhone SE (14.2), iPhone 6+(12.4.5), Redmi Note 8 (9.0), One plus 6T (10)
**Test Account:** (757) 699-9899/ [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B7)
**Pre Condition:** Make sure user should select “Celo” in select a digital currency & “cUSD/CELO address in “Receive funds in:
**Repro Steps:**

1. Launch the application and login with a test account.
2. Go to Home screen & tap on Hamburger menu 
3. Tap on “Add & Withdraw” 
4. Tap on Cashout & select Celo & cUSD/CELO address
5. paste any account key 
6. Enter amount more than available 
7. Observe

**Query:** Error banner messages should show if user enter more than available amount.
**Attachment:** [ErrorMessage.mp4](https://drive.google.com/file/d/1vCJEAlMhJ-UlpCASazbwjWAm5GBDQNCh/view?usp=sharing)

**Comment by tarikbellamine** [comment]
This is ok. We should be consistent but I just needed you to check the cUSD cash-out through the Bank Account method. Thanks!

**Comment by Celoqa** [comment]
Thanks @tarikbellamine for giving clarification.
