### ISSUE TITLE
Document supported deeplinks

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/wallet#468]
Document:
- pay deeplink (`celo://wallet/pay?...`)
- Dappkit / WalletConnect

This is a first pass at this, doesn't have to be complete, but should give enough pointers.

**Comment by bitmamahq** [comment]
Nice.. My first question with the pay deeplink `celo://wallet/pay?...` what are all the options (query parameters) i can add to the url?

**Comment by jeanregisser** [comment]
Hey @bitmamahq. please have a look at this https://discord.com/channels/600834479145353243/743997816363286568/814101258733748314
