### ISSUE TITLE
“404 This page could not be found” error message is displayed when the user clicks on “Add funds to your Valora Account” deeplink on “Send , Eran,Or spend your money with valora”> Valoraapp.com page 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#474]
**Frequency:** 100%
**Repro on build version:** Play store build 1.14, App store build V1.14, Android Internal build 1.15.1, Testflight V1.15.1(64)
**Repro on devices:** Samsung Galaxy Note 5 Pro(7.0), iphone 11(14.6), iPhone 6+(12.4.5), Vivo V11 pro (10)
**Test Account:** Frequent mom supreme illness plastic fog floor review lion cruise hurt movie game dentist zero iron crime drill scout face abandon mother beyond marble

 **Repro Steps:**

1. Launch the application & Login with test account 
2. Go to home page
3. Go to the 5th CTA i.e., “Send,earn or spend your money with valora”
4. Click on “Learn more” button
5. Scroll the page down 
6. Go to “Setting up your Valora account” 
7. Click on “Add funds to your valora account” deep link shown in point 4
8. Observe the redirected page

**Current Behavior:** “404 This page could not be found” error message is displayed when the user clicks on “Add funds to your Valora Account” deeplink
**Expected Behavior:**  The page related to “Add funds to your valora account” should be displayed when user tap on  “Add funds to your valora account” deep link
**Impact:** Bad user experience as the user gets no information about  how  to add funds into valora account
**Attachment:** [pagenotfount.mp4](https://drive.google.com/file/d/1mYgsDSL3cCJv9ShWm4XcMubv_44NKqr5/view?usp=sharing)

**Comment by MuckT** [comment]
@Celoqa can you please retest this issue. I am not able to reproduce this behavior.
[Video - Learn More Valoraapp.com](https://drive.google.com/file/d/1SK43ftqIB_mxSySw0a_YV33tn6fPGcTx/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @MuckT , We have verified this issue on both builds app store & play store V1.14 and Android internal build & Test Flight build V1.15 
**Observations:** 

- [ ] Users are able to see the "valoraapp.com" page when they click on "Add funds to your valora account" deeplink on “Send , Earn,Or spend your money with valora”> Valoraapp.com page. Hence, we are closing this ticket.

**Verified On Devices:**  Samsung Galaxy Note 5 Pro(7.0), iphone 11(14.6), iPhone 6+(12.4.5)
**Attachment:** [UserIsAbleToSeeValoraap.comPageWithoutError](https://drive.google.com/file/d/1lRemFDfNW2nzHMTpoBhzYb0pogP6hExv/view?usp=sharing)
