### ISSUE TITLE
Add a a 🔒  icon on top of the simplex flow

### ISSUE THREAD

**Issue by gnardini** [celo-org/wallet#491]
### What would you like?

See
https://celo-org.slack.com/archives/C018VLA3YAK/p1623437911082800

**Comment by tarikbellamine** [comment]
While I understand the concern, there is currently no way to allow WebView to display the full URL and we can't use InAppBrowser because Simplex requires us to render custom HTML, which is only supported on WebView.

As noted in the thread, manually adding a lock icon doesn't accomplish much.
