### ISSUE TITLE
Fix clock drift calculation

### ISSUE THREAD

**Issue by gnardini** [celo-org/wallet#544]
The SetClock screen is opening when it shouldn't for many users.

Here's the code that calculates the time drift: https://github.com/celo-org/wallet/blob/main/packages/mobile/src/utils/time.ts#L294

We're first calling _Date.now()_ and then _getRemoteTime_, which makes a network request. If the request takes more than 4 seconds (the drift threshold) the date might be outdated and fail even when it shouldn't.

Improve this calculation. One idea is to get a _startingTime_ and _endTime_, before and after making the remote time request and check that the remote time is between `startingTime - 4s` and `endTime + 4s`

**Comment by jeanregisser** [comment]
Possible fix:
- disable clock out of sync screen when forno is enabled
- use ntp for determining the actual skew, and check whether the React Native impl works correctly with regard to messages being passed over the bridge
