### ISSUE TITLE
User address is sometimes cutoff on the Send/Request Confirmation screen

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/wallet#620]
**Frequency:** 100%
**Repro App version:**  Test Flight build Valora app build  v1.1.0 (21) , Android Valora Mainnet build v1.1.0 (1004294309)
**Repro on device:** iPhone 7+ (13.3.1), Google Pixel Xl (8.1) 
**Test Account:** Backup Key: (757) 699-9899. 

**Repro Steps:**
1. Launch the Application and sign in with a test account from device 1 
2.  Launch the app and sign up with test account from device 2. 
3. Send payment request to user b using device 1. 
4. Tap on the Send button for payment request from Device 2. 
5. Observe User address. 

**Current Behavior:**  User address is cut on the “Sending” screen
**Expected Behavior:**  User address should not cut. 
**Impact:** User dont get the other user's address from sending screen. 
**Attachment:** Address.png. 

![Address](https://user-images.githubusercontent.com/55572027/92992438-982f4680-f508-11ea-9f88-0142181e072a.PNG)

**Comment by Celoqa** [comment]
We have verified this issue on latest android internal build V1.15.2 & Testflight build V1.15.2 (65) and found issue is fixed so, we are closing this ticket.
  **Attachment:** [AccountNumberOverlap.jpg](https://drive.google.com/file/d/1y3Mh-8SPdtiwvioBalXRhLLQutW7ajWm/view?usp=sharing)
