### ISSUE TITLE
User not able to receive Attestation codes when user try to complete signup flow through Restore my account section.

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#65]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.11.0(1004294337), Test Flight Build V1.11.0(47)
**Does not Repro on build version:** Playstore build V1.10.1, App store build V1.10.1,
**Repro on devices:** iPhone 6 + (12.4.5), Samsung galaxy J7 pro (8), iPhone 6s (14.2), iPhone XR (14.4)
Testing Account: [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5) 
  **Repro Steps:**

1. Launch the application 
2. Go through tutorials 
3. Tap on Restore my account button
4. enter name & tap on next button 
5. Enter valid account account key to restore 
6. Tap on restore button
7. Enter any valid phone number 
8. Complete captcha 
9. Wait for 2 mins time 
10. Observe 

**Current Behavior:** User not received any Attestation code 
**Expected Behavior:** user should receive the codes without any verification fail. 
**Observation:** 

1. Verification failed error message is shown when user try to complete signup flow.
2. From Confirm CTA: User not able to receive codes when go through CTA.

**Impact:** User get blocked to complete the signup flow .
**Attachment:**  [NotReceivedAttestation.mp4](https://drive.google.com/file/d/1-MSAtoDK2yDQ5jcGt_nhYHgAuExha-wF/view?usp=sharing)

**Comment by Celoqa** [comment]
Hi @i1skn We have verified this issue on latest android internal build 1.11.1 & testflight build 1.11.1(48) and found issue is fixed. 
- User is able to receive the attestation and able to complete the signup flow.

**Device:** Samsung M31 (10), iPhone 7+ (14.2)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R19](https://valora.testquality.com/project/12128/testcase/282081/requirement/11273). Do not remove or edit.
