### ISSUE TITLE
The app crashes when the user taps on the “Moonpay” link on the “Add Funds” screen.  

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#78]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.11.0(1004294337) 
**Does not repro version** Test Flight Build V1.11.0(47)
**Repro on devices:** Samsung Galaxy A5(7.0),  Samsung Galaxy J7 pro (8.0)
**Does not repro devices** iPhone XR(14.4)
**Testing Account:**   (+49) 4976 78 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)   
**Pre-condition:** Users should login with Germany Country phone number.
  **Repro Steps:**
1. Launch the application & login with a test account.
2. Now tap on Hamburger Menu & tap on “Add & Withdraw” option.
3. Now go to the “Add Funds” section & select “Celo dollar(cUSD)” from Select digital Currency field & “Debit card or bank account” from Pay with field.
4. Now enter $20 in the amount field & tap on Next button.
5. Now tap on the Moonpay link.
6. Observed that,
**Current Behavior:**  The app crashes & the user gets blocked to complete the transaction.
**Expected Behavior:**  Users should be able to proceed transactions without any crash.
**Impact:** User gets blocked to complete the transaction.
**Investigation:** Also we have observed crashes when a user taps on the “Ramp” link on Add Funds screen.
**Attachment:**  [CrashOnMoonpay.mp4](https://drive.google.com/file/d/1yc4J4n8D6Y2eyDOdAL0EAmheTiDWzXOr/view?usp=sharing)
**Crash Log:** [celo_logs .txt](https://drive.google.com/file/d/1BZxo1gNgaQvIuENt7gLSsbD0cbV4s-M6/view?usp=sharing)

**Comment by ValoraQA** [comment]
The above ticket is duplicate of https://github.com/valora-inc/wallet/issues/70
