### ISSUE TITLE
Add fee estimates and icons to ProviderOptionsScreen

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/wallet#84]
Add back in the icons for providers and display fee estimates based on the payment type (i.e., debit or bank account) for each provider. Fee quotes can be obtained using provider APIs.

Simplex: https://integrations.simplex.com/wallet-api-integration#getQuote
Moonpay: https://www.moonpay.com/dashboard/api_reference/client_side_api#get_currency_buy_quote
Transak: https://transak.stoplight.io/docs/transak-docs/1.swagger.yaml/paths/~1currencies~1price/get
Ramp: N/A

Designs: https://www.figma.com/file/p8oRC3AxLY5ABIxOuVAvxO/CICO?node-id=1119%3A5108

![Screen Shot 2021-03-02 at 5.18.48 PM.png](https://images.zenhubusercontent.com/5f88f410db540b09bbb09776/1bbd65fe-2cff-44b0-8e6a-165df9079628)

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R27](https://valora.testquality.com/project/12128/testcase/286109/requirement/11360). Do not remove or edit.
