### ISSUE TITLE
Create CicoSuccessScreen

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/wallet#85]
### Expected Behavior

The CicoSuccessScreen is shown when a user has successfully completed the CICO flow.

### Current Behavior
User is redirected to Home upon completion.

Designs: https://www.figma.com/file/p8oRC3AxLY5ABIxOuVAvxO/CICO?node-id=1119%3A5108

**Comment by calrobertlee** [comment]
Figma Screen: https://www.figma.com/file/p8oRC3AxLY5ABIxOuVAvxO/CICO?node-id=1374%3A6
