### ISSUE TITLE
Sell CELO screen has the wrong title.

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/wallet#865]
When inputting the amount during the Sell CELO flow, the screen is titled "Buy CELO".
It should be titled "Sell CELO"

**Comment by MuckT** [comment]
@dominiquejane. I am not seeing this reproduce on the Sell CELO flow. Can you confirm and provide screenshots of the screen in question?

Screenshot:
![Simulator Screen Shot - iPhone 11 - 2021-07-09 at 18 38 58](https://user-images.githubusercontent.com/26950305/125148143-0c188c00-e0e5-11eb-86e4-cb9c4b9aad2c.png)

**Comment by dominiquejane** [comment]
@MuckT It's the screen right before the one you posted, where you enter the amount.
I suspect it only occurs when you have 0 cEUR. I sold CELO for cEUR and when I went back to check after seeing your comment it no longer has the title.
Corey posted a similar experience: [slack convo](https://valora-app.slack.com/archives/C018VLA3YAK/p1625791621142500)

**Comment by aleksey-nov** [comment]
I can confirm what Dominique said. I saw buy Celo title when my account had 0 cEUR.

**Comment by MuckT** [comment]
https://valora.testquality.com requirement [R75](https://valora.testquality.com/project/12128/testcase/295427/requirement/11619).

**Comment by Celoqa** [comment]
Hi @MuckT We have verified this issue on Latest Test flight build V1.17.0 and updated the status in test quality tool.

Test quality tool link:

**iOS(12.5.4):**
- https://valora.testquality.com/project/12128/plan/21240/run/149557/result/2450204

Verified On Devices: iPhone SE (14.2), Samsung Galaxy S4 (4.4.2), iPhone 6+(12.5.4)
