### ISSUE TITLE
[Query]“Celo Euro” is shown disable on Add funds page 

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#869]
**Frequency:** 100%
**Repro on build version:** Android internal build V1.16.1 , Test Flight Build V1.16.1(67)
**Repro on devices:** iPhone SE (14.2), Redmi Note 8 (9.0), iPhone 6+(12.4.5), Vivo V11 pro (10)
**Testing Account:** (680) 333-1978/ [Backup Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B9) 
  **Repro Steps:**

1. Launch the application & login with a test account.
2. Tap on hamburger menu
3. Tap on add & withdraw button
4. Tap on add funds button
5. Observe ,

**Actual Result:** Celo Euro is shown disable in add funds page 
**Expected Result:** User should able to see Celo Euro enable.
**Attachment:** [CeloEuroDisable.mp4](https://drive.google.com/file/d/1xZlP-hhFv-9OfQ_b5leNNFZsB24m8Ott/view?usp=sharing)

**Comment by MuckT** [comment]
@tarikbellamine can you confirm if the above steps are correctly reproducing a defect?

**Comment by MuckT** [comment]
@Celoqa this is expected behavior, 'Add Fund' with cEUR can be enabled from the backend and is not currently due work needed with CICO providers. @tarikbellamine please correct me if this is wrong.

**Comment by Celoqa** [comment]
Thanks you @MuckT for comment. We will take a note of it:-)

**Comment by ValoraQA** [comment]
Hey @MuckT We have checked this query in V1.19.0 & observed that "Celo Euro(cEUR)" option is enabled on "Add Funds" page
**Verified On Devices:** Redmi Note 8 (9.0)
CC: @tarikbellamine
