### ISSUE TITLE
User able to take screenshot & also able to record account key using external app

### ISSUE THREAD

**Issue by Celoqa** [celo-org/wallet#88]
**Frequency:** 100%
**Repro on Devices:** Samsung Galaxy A5(7.0),  iPhone XR (14.4), iPhone 6s (14.2), Samsung Galaxy J7 pro (8.0)
**Repro version :** Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47)
**Login credential :** 515 444 0200 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B5)
**Repro Steps:**
1. Launch the application & login with a test account.
2. Setup Account key.
3. Now open the Account key from Hamburger Menu.
4. Now start screen recording on Your Account Key page.
5. Now try to take a screenshot of the Account key.
6. Observed that, User able to take screenshot & also able to record account key.
**Query :** User should not be able to take a screenshot & also blank black screen should display in recording instead of user’s account key.
**Investigation:** Before some builds we have observed that proper error message is displayed if user try to take screenshot & also blank screen was displaying in record.
**Impact:** User B can easily steal fund of User A by saving his account key.
**Attachment:** [UserAbleToRecord&ScreenshotAccounKey.mp4](https://drive.google.com/file/d/1Dbk6dx5QUkjas84yVf__vqNOkaWMb_Tw/view?usp=sharing)

**Comment by aleksey-nov** [comment]
We are moving away from the seed phrase, this should not be a problem anymore in the future.
