### ISSUE TITLE
Capitalize provider names on the CICO success screen

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/wallet#888]
Provider names display as lowercase on the CICO success screen

**Comment by Celoqa** [comment]
Hi @MuckT we have verified this issue on latest testflight build V1.17.0 (71) and updated the status in sheet:

**Sheet**

iOS (12.5.4):
- https://docs.google.com/spreadsheets/d/1ao96faipCyUg2qddMS3HyG-edNrt5ew7Xqg12Srt1oc/edit#gid=1142225835

**Devices:** iPhone 6+(12.5.4)

**Note:** As we are able to see improper text on exchanges [CoinList Pro, OKCoin, Bittrex] capital letters are used in the middle of the text. [ImproperOrder.jpg](https://drive.google.com/file/d/1M_8C8odWwmsdK1Ye82grmd7cZRre5zln/view?usp=sharing)

**Comment by MuckT** [comment]
@Celoqa this is known as _Bicapitalization_ some popular examples include DreamWorks, YouTube, FedEx, & PepsiCo.

CoinList Pro, OKCoin and Bittrex all look correct in the attached screenshot.

**Comment by Celoqa** [comment]
Hi @MuckT thanks for giving confirmation.
