### ISSUE TITLE
Valora cEUR Invites Showing a Large Number of Significant Digits 

### ISSUE THREAD

**Issue by MuckT** [celo-org/wallet#908]
### Issue

Sending an invite with cEUR to a new user shows a large amount of significant digits.

### Current behavior

When a user receives an invite a large number of significant digits are displayed.

### Desired behavior

Users receiving an invite should only see hundredths or thousandths e.g. '1.01' or '1.001'

### Steps to Reproduce

- Send a user an invite to use Valora with an '.5' cEUR
- Observe SMS on recipient phone

### Versions

v1.16.2

### Screenshots

![Screenshot_20210719-214135](https://user-images.githubusercontent.com/26950305/126219370-97d029ef-a42b-47d4-a911-1c469feff687.png)

**Comment by Celoqa** [comment]
Hey @MuckT I have verified this issue using Test flight build V1.17.0 & Android internal build V1.17.0 & observed that issue is reproduced for us.
**Verified On Devices:** Redmi Note 8 (9.0), iPhone SE (14.2)
**Attachment:** [LongAmountForcEUR](https://drive.google.com/file/d/16iwDg7ViumzXghrA0Q9-dUbNDP9YoLWd/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest Android internal build V1.18.0 and updated the status in test quality tool.

Test quality tool link:

Android (11):
https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469326

**Verified on Devices:** Google Pixel 4a (11.0)

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest Android Internal build V1.18.0 and updated the status in test quality tool.

Test quality tool link:

Android (10.0):
https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469315

**Verified on Devices:** Redmi Note 8 (10.0)
Thanks..!!

**Comment by ValoraQA** [comment]
Hi @MuckT We have verified this issue on Latest  Test Flight build V1.18.0 updated the status in test quality tool.

**Test quality tool link:**
- https://valora.testquality.com/project/12128/plan/21657/run/149950/result/2469271

**Verified on Devices:** iPhone SE (13.6.1)
Thanks..!!
